version: '3.8'

services:
  report_api:
      build:
        context: .
      ports:
        - "8080:8080"
      environment:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        FRON_URL: ${FRON_URL}
      networks:
        - api_user
      depends_on:
        - postgis
      restart: always

  postgis:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: geo_report_DB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_user

networks:
  api_user:

volumes:
  pgdata: